version: v1.0
name: build-step
jobs:
- job: First job
  steps:
  - checkout: '{{.cds.workspace}}'
  - script: mvn package
  - artifactUpload:
      path: '{{.cds.workspace}}target/*.jar'
  requirements:
  - binary: git
