version: v1.0
name: MyPipeline
jobs:
- job: First job
  steps:
  - checkout: '{{.cds.workspace}}'
  - script : mvn package
  - artifactUpload : target/*.jar 
  requirements:
  - binary: mvn
  - binary: git
