name: cdsdemo
version: v1.0
workflow:
  build:
    application: cdsdemo
    pipeline: build-pipeline
    payload:
      git.author: ""
      git.branch: master
      git.hash: ""
      git.hash.before: ""
      git.message: ""
      git.repository: nielsonsantana/cdsdemo
      git.tag: ""
    # pipeline_hooks:
    # - type: Scheduler
    #   config:
    #     cron: 0/30 * * * *
    #     payload: '{}'
    #     timezone: UTC
hooks:
  build:
  - type: Git Repository Poller
    config:
      payload: '{}'