name: cdsdemo
version: v1.0
workflow:
  build:
    application: cdsdemo
    pipeline: build-step
    payload:
      git.author: ""
      git.branch: master
      git.hash: ""
      git.hash.before: ""
      git.message: ""
      git.repository: nielsonsantana/cdsdemo
      git.tag: ""
    # pipeline_hooks:
    # - type: Scheduler
    #   config:
    #     cron: 0/30 * * * *
    #     payload: '{}'
    #     timezone: UTC
hooks:
  - type: Git Repository Poller
    config:
      payload: '{}'
  - type: WebHook
    method: GET
    url: https://www.google.com.br
metadata:
  default_tags: git.branch,git.author
