name: cdsdemo
version: v1.0
workflow:
  build:
    application: cdsdemo
    pipeline: build-pipeline
    payload:
      git.branch: "master"
      git.repository: nielsonsantana/cdsdemo
    pipeline_hooks:
    - type: Git Repository Poller
    # pipeline_hooks:
    # - type: Scheduler
    #   config:
    #     cron: 0/30 * * * *
    #     payload: '{}'
    #     timezone: UTC